/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as SellRouteImport } from './routes/sell'
import { Route as AssetsTokenIdRouteImport } from './routes/assets_.$tokenId'
import { Route as BuyServiceIdRouteImport } from './routes/buy_.$serviceId'
import { Route as ListingTokenIdRouteImport } from './routes/listing.$tokenId'
import { Route as SellTokenIdRouteImport } from './routes/sell_.$tokenId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsTokenIdRoute = AssetsTokenIdRouteImport.update({
  id: '/assets_/$tokenId',
  path: '/assets/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyServiceIdRoute = BuyServiceIdRouteImport.update({
  id: '/buy_/$serviceId',
  path: '/buy/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingTokenIdRoute = ListingTokenIdRouteImport.update({
  id: '/listing/$tokenId',
  path: '/listing/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellTokenIdRoute = SellTokenIdRouteImport.update({
  id: '/sell_/$tokenId',
  path: '/sell/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/buy': typeof BuyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/provider': typeof ProviderRoute
  '/sell': typeof SellRoute
  '/assets/$tokenId': typeof AssetsTokenIdRoute
  '/buy/$serviceId': typeof BuyServiceIdRoute
  '/listing/$tokenId': typeof ListingTokenIdRoute
  '/sell/$tokenId': typeof SellTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/buy': typeof BuyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/provider': typeof ProviderRoute
  '/sell': typeof SellRoute
  '/assets/$tokenId': typeof AssetsTokenIdRoute
  '/buy/$serviceId': typeof BuyServiceIdRoute
  '/listing/$tokenId': typeof ListingTokenIdRoute
  '/sell/$tokenId': typeof SellTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/buy': typeof BuyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/provider': typeof ProviderRoute
  '/sell': typeof SellRoute
  '/assets_/$tokenId': typeof AssetsTokenIdRoute
  '/buy_/$serviceId': typeof BuyServiceIdRoute
  '/listing/$tokenId': typeof ListingTokenIdRoute
  '/sell_/$tokenId': typeof SellTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/buy'
    | '/how-it-works'
    | '/marketplace'
    | '/provider'
    | '/sell'
    | '/assets/$tokenId'
    | '/buy/$serviceId'
    | '/listing/$tokenId'
    | '/sell/$tokenId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/buy'
    | '/how-it-works'
    | '/marketplace'
    | '/provider'
    | '/sell'
    | '/assets/$tokenId'
    | '/buy/$serviceId'
    | '/listing/$tokenId'
    | '/sell/$tokenId'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/buy'
    | '/how-it-works'
    | '/marketplace'
    | '/provider'
    | '/sell'
    | '/assets_/$tokenId'
    | '/buy_/$serviceId'
    | '/listing/$tokenId'
    | '/sell_/$tokenId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  BuyRoute: typeof BuyRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ProviderRoute: typeof ProviderRoute
  SellRoute: typeof SellRoute
  AssetsTokenIdRoute: typeof AssetsTokenIdRoute
  BuyServiceIdRoute: typeof BuyServiceIdRoute
  ListingTokenIdRoute: typeof ListingTokenIdRoute
  SellTokenIdRoute: typeof SellTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets_/$tokenId': {
      id: '/assets_/$tokenId'
      path: '/assets/$tokenId'
      fullPath: '/assets/$tokenId'
      preLoaderRoute: typeof AssetsTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy_/$serviceId': {
      id: '/buy_/$serviceId'
      path: '/buy/$serviceId'
      fullPath: '/buy/$serviceId'
      preLoaderRoute: typeof BuyServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$tokenId': {
      id: '/listing/$tokenId'
      path: '/listing/$tokenId'
      fullPath: '/listing/$tokenId'
      preLoaderRoute: typeof ListingTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell_/$tokenId': {
      id: '/sell_/$tokenId'
      path: '/sell/$tokenId'
      fullPath: '/sell/$tokenId'
      preLoaderRoute: typeof SellTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  BuyRoute: BuyRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketplaceRoute: MarketplaceRoute,
  ProviderRoute: ProviderRoute,
  SellRoute: SellRoute,
  AssetsTokenIdRoute: AssetsTokenIdRoute,
  BuyServiceIdRoute: BuyServiceIdRoute,
  ListingTokenIdRoute: ListingTokenIdRoute,
  SellTokenIdRoute: SellTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
